/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_wel4j_WindowsEventLogImpl */

#ifndef _Included_org_wel4j_WindowsEventLogImpl
#define _Included_org_wel4j_WindowsEventLogImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wel4j_WindowsEventLogImpl
 * Method:    reportEvent
 * Signature: (Ljava/lang/String;Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_org_wel4j_WindowsEventLogImpl_reportEvent
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
